version: "3.9"
services:
  db:
    image: postgres:15.1
    volumes:
      - "postgres:/data/postgres"
    environment:
      POSTGRES_PASSWORD: password
      BUNDLE_FORCE_RUBY_PLATFORM: "true"
      PGDATA: /data/postgres
    ports:
      - "6543:5432"

  redis:
    image: 'redis:7.0.8'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec sidekiq -C ./config/sidekiq.yaml
    volumes:
      - '.:/elastic-products'
      - .:/tmp/sidekiq' # don't mount tmp directory
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1

  server:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/elastic-products
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - elasticsearch
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.16
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.16
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
volumes:
  redis:
  postgres:
